title: <Your Name>
description: <Your Description>
theme: jekyll-theme-cayman

title: mohamed
description: A cool guy
instagram_username: mohamed_hani_10
github_username: moHani11
theme: jekyll-theme-cayman